import './globals.css'

import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import { cn } from '@/lib/utils'

import { ThemeProvider } from '@/components/providers/theme-provider'

const font = Roboto({ weight: ["100", "300", "400", "500", "700", "900"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Carotempo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt" suppressHydrationWarning>
      <body className={cn(font.className, "bg-white dark:bg-[#0B131E]")}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey='carotempo-theme'>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
